/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package THpaneles;

import THVentanas.VentanaPrincipal;
import THlogica.grupo;
import THlogica.grupos;
import java.awt.Color;
import javax.swing.SwingUtilities;


public class GroupCard extends javax.swing.JPanel {
    
    private String namee = "";
    private String semester = "1";
    private int curses = 0;
    
    
    private VentanaPrincipal ventana;
    private grupo thisGrupo;
    private grupos thisGrupos;
    
    private boolean chosen = false;
    
    public GroupCard() {
        initComponents();
        
    }
    
    public void convertTextToColor(String text) {
        int hashCode = text.hashCode();
        this.jPanel1.setBackground(new Color(hashCode));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        data = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(false);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setDoubleBuffered(false);
        bg.setRequestFocusEnabled(false);
        bg.setVerifyInputWhenFocusTarget(false);
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        bg.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(8, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg.add(jPanel1);
        jPanel1.setBounds(0, 0, 8, 60);

        data.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        data.setForeground(new java.awt.Color(204, 204, 204));
        data.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        data.setText("2 semestre | 3 cursos");
        bg.add(data);
        data.setBounds(70, 40, 190, 15);

        name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(104, 104, 104));
        name.setText("Ing. Civil");
        bg.add(name);
        name.setBounds(30, 10, 180, 30);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(125, 125, 125));
        delete.setText("x");
        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFocusPainted(false);
        delete.setRequestFocusEnabled(false);
        delete.setSelected(true);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                deleteComponentMoved(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        bg.add(delete);
        delete.setBounds(270, 0, 30, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        
        if (!this.chosen) {
            ventana.unchoseChosen();
            ventana.setGroupChosen(this.thisGrupo);
            ventana.setGroupchoosen(this);

            ventana.UpdateCursoCards();
            ventana.UpdateOpcionCards();
            
            this.chosen = true;
            chose();
        } else {
            ventana.unchoseChosen();
            this.chosen = false;
            this.unchose();
            ventana.UpdateCursoCards();
            ventana.UpdateOpcionCards();
        }
        
        
    }//GEN-LAST:event_bgMouseClicked

    private void deleteComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteComponentMoved
//        System.out.println("JUJUJU  " + this.delete.getX() + "   " + this.delete.getY()); //
        
        if (this.chosen) {
            chose();
        } else{
            unchose();
        }
    }//GEN-LAST:event_deleteComponentMoved

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        thisGrupos.deletegrupo(thisGrupo.getName());
        
        ventana.UpdateGroupCards();
        ventana.UpdateCursoCards();
        ventana.UpdateOpcionCards();
        ventana.unchoseChosencurso();
        ventana.unchoseChosenopcion();
        ventana.unchoseChosen();
    }//GEN-LAST:event_deleteActionPerformed
    
    
    private void chose(){
        SwingUtilities.invokeLater(() -> {
            this.data.setLocation(30,40);
            this.delete.setLocation(230,0);
            this.delete.setEnabled(true);
            
            this.jPanel1.setSize(18,60);
            
            this.bg.repaint();
        });
    }
    
    
    public void unchose(){
        SwingUtilities.invokeLater(() -> {
            this.data.setLocation(70,40);
            this.delete.setLocation(270,0);
            this.delete.setEnabled(false);
            
            this.jPanel1.setSize(6,60);
            
            this.bg.repaint();
        });
    }
    
    
    
    

    //<editor-fold defaultstate="collapsed" desc=" setters y getters">
    
    public void setChosen(boolean chosen) {
        this.chosen = chosen;
    }  
    
    
    public String getNamee() {
        return namee;
    }

    public void setNamee(String name) {
        this.namee = name;
    }

    public String getSemester() {
        return semester;
    }

    public void setSemester(String semester) {
        this.semester = semester;
    }

    public int getCurses() {
        return curses;
    }

    public void setCurses(int curses) {
        this.curses = curses;
    }

    public boolean isChosen() {
        return chosen;
    }
    
    //</editor-fold>
    
    public VentanaPrincipal getVentana() {
        return ventana;
    }

    public void setVentana(VentanaPrincipal ventana) {
        this.ventana = ventana;
    }

    public grupo getThisGrupo() {
        return thisGrupo;
    }

    public void setThisGrupo(grupo thisGrupo) {
        this.thisGrupo = thisGrupo;
        this.namee = this.thisGrupo.getName();
        this.curses = this.thisGrupo.contar();
        this.semester = this.thisGrupo.getSemestre();
        
        this.name.setText(namee);
        this.data.setText("Semestre " + this.semester + " | " + this.curses + " cursos");
        this.convertTextToColor(namee);
    }

    public grupos getThisGrupos() {
        return thisGrupos;
    }

    public void setThisGrupos(grupos thisGrupos) {
        this.thisGrupos = thisGrupos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel data;
    private javax.swing.JButton delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
