/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package THpaneles;

import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import THVentanas.VentanaPrincipal;
import THlogica.opcion;
import THlogica.opciones;
import javax.swing.SwingUtilities;

public class OptionCard extends javax.swing.JPanel {
    opciones variable;
    VentanaPrincipal padre;
    
    int[] disabled  = {187,187,187};
    int[][] hour = {{255,255,255},{255,255,204},{255,204,153},{94,101,232},{47,85,151}};
    
    private int He = 2;
    private int Hs = 5;
    private int day = 0;
    
    
    private VentanaPrincipal ventana;
    private opcion thisOpcion;
    private opciones thisOpciones;

    
    private boolean chosen = false;
    
    
    public OptionCard() {
        setSize(180, 30);
        initComponents();
        this.del.setVisible(false);
        
    }
    
    @Override
    protected void paintComponent(Graphics gg){
        
        Graphics2D g2 = (Graphics2D) gg.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(this.getBackground());
        g2.fill(new RoundRectangle2D.Double(0,0, 180, 30, 30,30));
        g2.dispose();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        del = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 239, 237));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 65)); // NOI18N
        sun.setForeground(new java.awt.Color(47, 85, 151));
        sun.setText("•");
        sun.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                sunComponentMoved(evt);
            }
        });
        add(sun, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, -27, 30, 80));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("JUE   12 AM - 2 PM");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, 130, -1));

        del.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        del.setForeground(new java.awt.Color(102, 102, 102));
        del.setText("x");
        del.setBorder(null);
        del.setBorderPainted(false);
        del.setContentAreaFilled(false);
        del.setEnabled(false);
        del.setFocusPainted(false);
        add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.chosen = true;
        chose();
    }//GEN-LAST:event_formMouseClicked

    private void sunComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sunComponentMoved
        if (this.chosen) {
            chose();
        } else{
            unchose();
        }
    }//GEN-LAST:event_sunComponentMoved
    
    
    
    private void chose(){
        SwingUtilities.invokeLater(() -> {
            this.sun.setLocation(130,this.sun.getY());
            this.setBackground(Color.white);
            this.del.setEnabled(true);
            this.del.setVisible(true);
        });
    }
    
    
    public void unchose(){
        SwingUtilities.invokeLater(() -> {
            this.sun.setLocation(153,this.sun.getY());
            this.setBackground(new Color(disabled[0],disabled[1],disabled[2]));
            this.del.setEnabled(false);
            this.del.setVisible(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel sun;
    // End of variables declaration//GEN-END:variables
}
