/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package THVentanas;

import THlogica.grupos;
import java.awt.MouseInfo;
import java.awt.PointerInfo;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    grupos grupos = new grupos();
    
    public VentanaPrincipal() {
        
        initComponents();
        grupos.ReadGrupos();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/THimages/icon.png")));
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),24,24));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        move = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        switchven = new javax.swing.JTabbedPane();
        edit = new javax.swing.JPanel();
        Gruposed = new javax.swing.JPanel();
        gruptitle = new javax.swing.JLabel();
        newgup = new javax.swing.JButton();
        cursosed = new javax.swing.JPanel();
        newgup1 = new javax.swing.JButton();
        gruptitle1 = new javax.swing.JLabel();
        newgup2 = new javax.swing.JButton();
        newgup3 = new javax.swing.JButton();
        opcionsed = new javax.swing.JPanel();
        newgup4 = new javax.swing.JButton();
        newgup5 = new javax.swing.JButton();
        newgup6 = new javax.swing.JButton();
        gruptitle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(169, 209, 142));
        header.setPreferredSize(new java.awt.Dimension(1180, 95));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        move.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        move.setForeground(new java.awt.Color(102, 204, 255));
        move.setText("•");
        move.setToolTipText("");
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        header.add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, -10, -1, 50));

        min.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 102));
        min.setText("•");
        min.setToolTipText("");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        header.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, -10, -1, 50));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 102, 102));
        exit.setText("•");
        exit.setToolTipText("");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, -10, -1, 50));

        name.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("#TUHORARIO");
        header.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/THimages/icons8_edit_45px_2.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        header.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 40, 40));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 60));

        switchven.setBackground(new java.awt.Color(237, 253, 246));
        switchven.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        switchven.setToolTipText("");

        edit.setBackground(new java.awt.Color(204, 204, 204));
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gruposed.setBackground(new java.awt.Color(237, 253, 246));
        Gruposed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gruptitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        gruptitle.setForeground(new java.awt.Color(127, 127, 127));
        gruptitle.setText("Grupos");
        Gruposed.add(gruptitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 20));

        newgup.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup.setForeground(new java.awt.Color(127, 127, 127));
        newgup.setText("+");
        newgup.setBorder(null);
        newgup.setContentAreaFilled(false);
        newgup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gruposed.add(newgup, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 20, 20));

        edit.add(Gruposed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 670));

        cursosed.setBackground(new java.awt.Color(209, 243, 222));
        cursosed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newgup1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup1.setForeground(new java.awt.Color(127, 127, 127));
        newgup1.setText("+");
        newgup1.setBorder(null);
        newgup1.setContentAreaFilled(false);
        newgup1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cursosed.add(newgup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 20, 20));

        gruptitle1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        gruptitle1.setForeground(new java.awt.Color(127, 127, 127));
        gruptitle1.setText("Cursos");
        cursosed.add(gruptitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 20));

        newgup2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup2.setForeground(new java.awt.Color(127, 127, 127));
        newgup2.setText("u");
        newgup2.setBorder(null);
        newgup2.setContentAreaFilled(false);
        newgup2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgup2ActionPerformed(evt);
            }
        });
        cursosed.add(newgup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 20, 20));

        newgup3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup3.setForeground(new java.awt.Color(127, 127, 127));
        newgup3.setText("l");
        newgup3.setBorder(null);
        newgup3.setContentAreaFilled(false);
        newgup3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgup3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgup3ActionPerformed(evt);
            }
        });
        cursosed.add(newgup3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 20, 20));

        edit.add(cursosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 300, 670));

        opcionsed.setBackground(new java.awt.Color(237, 253, 246));
        opcionsed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newgup4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup4.setForeground(new java.awt.Color(127, 127, 127));
        newgup4.setText("+");
        newgup4.setBorder(null);
        newgup4.setContentAreaFilled(false);
        newgup4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionsed.add(newgup4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 20, 20));

        newgup5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup5.setForeground(new java.awt.Color(127, 127, 127));
        newgup5.setText("l");
        newgup5.setBorder(null);
        newgup5.setContentAreaFilled(false);
        newgup5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgup5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgup5ActionPerformed(evt);
            }
        });
        opcionsed.add(newgup5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 20, 20));

        newgup6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        newgup6.setForeground(new java.awt.Color(127, 127, 127));
        newgup6.setText("u");
        newgup6.setBorder(null);
        newgup6.setContentAreaFilled(false);
        newgup6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newgup6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgup6ActionPerformed(evt);
            }
        });
        opcionsed.add(newgup6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 20, 20));

        gruptitle2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        gruptitle2.setForeground(new java.awt.Color(127, 127, 127));
        gruptitle2.setText("Opciones");
        opcionsed.add(gruptitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 20));

        edit.add(opcionsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 540, 670));

        switchven.addTab("tab1", edit);

        switchven.setSelectedIndex(0);

        getContentPane().add(switchven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1180, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();
        int x = pointerInfo.getLocation().x;
        int y = pointerInfo.getLocation().y;
        
        setLocation(x-move.getX()-15,y+move.getY()-25);
    }//GEN-LAST:event_moveMouseDragged

    private void newgup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgup2ActionPerformed

    private void newgup3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgup3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgup3ActionPerformed

    private void newgup5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgup5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgup5ActionPerformed

    private void newgup6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgup6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgup6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gruposed;
    private javax.swing.JPanel cursosed;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gruptitle;
    private javax.swing.JLabel gruptitle1;
    private javax.swing.JLabel gruptitle2;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel min;
    private javax.swing.JLabel move;
    private javax.swing.JLabel name;
    private javax.swing.JButton newgup;
    private javax.swing.JButton newgup1;
    private javax.swing.JButton newgup2;
    private javax.swing.JButton newgup3;
    private javax.swing.JButton newgup4;
    private javax.swing.JButton newgup5;
    private javax.swing.JButton newgup6;
    private javax.swing.JPanel opcionsed;
    private javax.swing.JTabbedPane switchven;
    // End of variables declaration//GEN-END:variables
}
